name: rb_share
description: "A new Flutter project."

publish_to: "none"

version: 1.0.1+6

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  app_group_directory: 2.0.0
  basic_utils: 5.7.0
  collection: ^1.17.2 # allow newer versions, so it can compile with newer Flutter versions
  common:
    path: common
  connectivity_plus: ^6.0.5
  dart_mappable: ^4.2.2
  desktop_drop: 0.4.4
  device_apps: 2.2.0
  device_info_plus: ^10.1.2
  dio: ^5.5.0+1
  dynamic_color: ^1.7.0
  file_picker: ^8.0.7
  file_selector: 1.0.3
  flutter:
    sdk: flutter
  flutter_displaymode: 0.6.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3+1
  google_fonts: ^6.2.1
  gal: 2.3.0
  image_picker: ^1.1.2
  in_app_purchase: ^3.2.0 # [FOSS_REMOVE]
  intl: ^0.19.0 # allow newer versions, so it can compile with newer Flutter versions
  launch_at_startup: ^0.3.1
  logging: 1.2.0
  macos_dock_progress: ^1.0.0
  mime: ^1.0.5
  network_info_plus: ^6.0.0
  open_filex: 4.4.0
  package_info_plus: ^8.0.2
  pasteboard: ^0.2.0
  path: 1.9.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pretty_qr_code: ^3.3.0
  refena_flutter: 1.6.0
  refena_inspector_client: 1.2.0
  routerino: 0.8.0
  saf_stream: 0.4.0 # Saving files to SD card for Android <11
  screen_retriever: 0.1.9
  share_handler: ^0.0.21
  share_handler_ios: ^0.0.14 # Keep iOS <14 support
  shared_preferences: ^2.3.1
  shared_preferences_platform_interface: any
  shared_storage: 0.8.1
  shelf: 1.4.1
  shelf_router: 1.1.4
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  system_settings: 2.1.0
  system_tray: 2.0.3
  tray_manager:
    # https://github.com/leanflutter/tray_manager/issues/30
    # The Linux tray manager is disabled for now
    git:
      url: https://github.com/Tienisto/tray_manager.git
      ref: b37f5e088e0f02c45a684ae41e9d2da2d5c596db
  url_launcher: ^6.3.0
  uuid: 3.0.7
  wakelock_plus: ^1.2.7
  wechat_assets_picker: ^9.0.2
  window_manager: ^0.4.0
  windows_taskbar: 1.1.2
  yaru: 1.2.2
  flutter_native_splash: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.2.3
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^4.0.0
  mockito: 5.4.4
  msix: 3.16.7
  refena_inspector: 1.2.0
  test: ^1.24.3
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  adaptive_icon_background: "#1D1B1E"
  adaptive_icon_foreground: "assets/logo.png"
  # ios: true
  image_path: "assets/logo-1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dependency_overrides:
  permission_handler_windows:
    # Remove windows support as it causes trouble with Windows 7
    # https://github.com/Baseflow/flutter-permission-handler/issues/1034
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
      ref: 2dadd8afbf81e0e3e4791d7144e689555e58f649

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/web/
    - assets/CHANGELOG.md

flutter_gen:
  line_length: 150

msix_config:
  display_name: RBShare
  publisher_display_name: Luan Batista
  # Using third-party CA for now (see: https://github.com/localsend/localsend/issues/220)
  # publisher: CN=0A8E9755-183F-4F0B-823F-1B8C991D7B97
  identity_name: 11157RBShare.rb
  logo_path: assets\img\logo-512.png
  architecture: x64
  languages: en, ar, bn, cs, da, de, el, es-ES, eu, fa, fr, he, hu, in, it, ja, ko, ne, nl, pl, pt-BR, ru, sv, th, tr, uk, vi, zh-CN, zh-HK, zh-TW

  # https://github.com/localsend/localsend/issues/398
  os_min_version: 10.0.19041.0

  startup_task:
    task_id: rbshare
    enabled: false
    parameters: autostart
